package com.model;

import java.util.Date;

public class Job {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_id
     *
     * @mbggenerated Fri Jun 05 19:38:00 CST 2020
     */
    private Integer jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_name
     *
     * @mbggenerated Fri Jun 05 19:38:00 CST 2020
     */
    private String jobName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_address
     *
     * @mbggenerated Fri Jun 05 19:38:00 CST 2020
     */
    private String jobAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_salary
     *
     * @mbggenerated Fri Jun 05 19:38:00 CST 2020
     */
    private Double jobSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.release_time
     *
     * @mbggenerated Fri Jun 05 19:38:00 CST 2020
     */
    private Date releaseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.cid
     *
     * @mbggenerated Fri Jun 05 19:38:00 CST 2020
     */
    private String cid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_id
     *
     * @return the value of job.job_id
     *
     * @mbggenerated Fri Jun 05 19:38:00 CST 2020
     */
    public Integer getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_id
     *
     * @param jobId the value for job.job_id
     *
     * @mbggenerated Fri Jun 05 19:38:00 CST 2020
     */
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_name
     *
     * @return the value of job.job_name
     *
     * @mbggenerated Fri Jun 05 19:38:00 CST 2020
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_name
     *
     * @param jobName the value for job.job_name
     *
     * @mbggenerated Fri Jun 05 19:38:00 CST 2020
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_address
     *
     * @return the value of job.job_address
     *
     * @mbggenerated Fri Jun 05 19:38:00 CST 2020
     */
    public String getJobAddress() {
        return jobAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_address
     *
     * @param jobAddress the value for job.job_address
     *
     * @mbggenerated Fri Jun 05 19:38:00 CST 2020
     */
    public void setJobAddress(String jobAddress) {
        this.jobAddress = jobAddress == null ? null : jobAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_salary
     *
     * @return the value of job.job_salary
     *
     * @mbggenerated Fri Jun 05 19:38:00 CST 2020
     */
    public Double getJobSalary() {
        return jobSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_salary
     *
     * @param jobSalary the value for job.job_salary
     *
     * @mbggenerated Fri Jun 05 19:38:00 CST 2020
     */
    public void setJobSalary(Double jobSalary) {
        this.jobSalary = jobSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.release_time
     *
     * @return the value of job.release_time
     *
     * @mbggenerated Fri Jun 05 19:38:00 CST 2020
     */
    public Date getReleaseTime() {
        return releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.release_time
     *
     * @param releaseTime the value for job.release_time
     *
     * @mbggenerated Fri Jun 05 19:38:00 CST 2020
     */
    public void setReleaseTime(Date releaseTime) {
        this.releaseTime = releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.cid
     *
     * @return the value of job.cid
     *
     * @mbggenerated Fri Jun 05 19:38:00 CST 2020
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.cid
     *
     * @param cid the value for job.cid
     *
     * @mbggenerated Fri Jun 05 19:38:00 CST 2020
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }
}